/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#9DBEBB',
        secondary: '#F4ACB7',
        accent: '#FFE5D9',
        'surface-page': '#FDFBF7',
        'surface-card': '#FFFFFF',
        'surface-soft': '#F7F3EC',
        'stroke-soft': '#E9E3DA',
        'text-strong': '#2D3648',
        'text-muted': '#5C635C',
        'accent-soft': '#FFF1EA',
        'accent-border': '#F7D4C2',
        'rose-soft': '#FCE8EE',
        'info-mist': '#C7DCE8',
        'brand-navy': '#2D3648',
        'background-light': '#FDFBF7',
        'background-dark': '#1A1C19',
        'brand-surface': '#FDFBF7',
        'cream': '#F3F0E6',
        surface: '#FFFFFF',
        warmgray: '#2D3648',
        'warmgray-muted': '#5C635C',
        border: '#e7e5e4',
        // New design system colors
        'sage-light': '#E8EFEA',
        'accent-sage': '#E6EBE6',
        'accent-dark-sage': '#2D352E',
        'off-white': '#FDFCFB',
        'soft-sand': '#F5EDE3',
        'quilt-pink': '#F8E9E9',
        'text-soft': '#5C635C',
        'card-white': '#FFFFFF',
        'accent-warm': '#E8D5C4',
        'card-light': '#FFFFFF',
        'card-dark': '#2D2D2A',
        // Added sage variants for contacts screen
        sage: {
          50: '#f6f8f7',
          100: '#e8efe9',
          200: '#d1e0d3',
          500: '#6b9c7c',
          700: '#436850',
        },
        stone: {
          50: '#fafaf9',
          100: '#f5f5f4',
          200: '#e7e5e4',
          300: '#d6d3d1',
          400: '#a8a29e',
          500: '#78716c',
        }
      },
      fontFamily: {
        display: ['PlayfairDisplay_500Medium'],
        'display-semibold': ['PlayfairDisplay_600SemiBold'],
        'display-italic': ['PlayfairDisplay_500Medium_Italic'],
        heading: ['Quicksand_400Regular', 'Quicksand_500Medium', 'Quicksand_600SemiBold', 'Quicksand_700Bold'],
        body: ['Outfit_300Light', 'Outfit_400Regular', 'Outfit_500Medium', 'Outfit_600SemiBold'],
      },
      borderRadius: {
        DEFAULT: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '24px',
        'pill': '100px',
        'inner-pill': '24px',
      },
      boxShadow: {
        soft: '0 10px 25px -5px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
};
